version: '3'

services:

#  projeto:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres
#    env_file:
#      - .env
#    networks:
#      - projeto
#    volumes:
#      - .:/app

  postgres:
    image: postgres:alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'Deluc@123'
      POSTGRES_DB: projeto-django
    volumes:
      - database:/var/lib/postgresql/data
#    networks:
#      - projeto


#networks:
#  projeto:
#    driver: bridge

volumes:
    database:
