# Generated by Django 4.0 on 2025-01-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=165)),
                ('tempo_preparo', models.IntegerField()),
                ('unidade_preparo', models.CharField(max_length=50)),
                ('unidades_porcao', models.IntegerField()),
                ('etapas_preparo', models.TextField()),
                ('etapas_preparo_is_html', models.BooleanField(default=False)),
                ('esta_publicado', models.BooleanField(default=True)),
                ('capa', models.ImageField(upload_to='receitas/capas/%Y/%m/%d/')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria')),
            ],
        ),
    ]
