# Generated by Django 4.0 on 2025-01-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='unidade_tempo',
            field=models.CharField(default='Minutos', max_length=30),
        ),
    ]
