# Generated by Django 4.0 on 2025-01-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('receitas', '0002_receita_unidade_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='autor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='capa',
            field=models.ImageField(blank=True, default='', upload_to='receitas/capas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitas.categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
